version: '3.7'
services:
    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            - ./data/postgres:/var/lib/postgresql/data:z
        networks:
            - pipeline_net
    webserver:
        build: .
        restart: always
        depends_on:
            - postgres
        environment:
            - LOAD_EX=n
            - EXECUTOR=Local
        logging:
            options:
                max-size: 10m
                max-file: "3"
        volumes:
            # - ./plugins:/usr/local/airflow/plugins
            - ./dags:/usr/local/airflow/dags
            - pipeline_store:/usr/local/airflow/data/
        networks:
            - pipeline_net
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

volumes:
  pipeline_store:
    external:
      name: pipeline_store
networks:
  pipeline_net:
    external: true
